config/routes.rb
Rails.application.routes.draw do
  root 'demo#home'
  get 'demo/download' => 'demo#download', as: :download
  post 'demo/show_options' => 'demo#show_options', as: :show_options
  post 'demo/hide_options' => 'demo#hide_options', as: :hide_options
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  respond_to :html, :js

  def home
  end

  def show_options
  end

  def hide_options
  end

  def download
    if params[:data]
      send_data render_to_string(partial: 'demo/download/data'),
                type: 'text/plain; charset=UTF-8;',
                filename: "Data #{Time.current.to_formatted_s(:db)}.txt"
    elsif params[:sample]
      send_data render_to_string(partial: 'demo/download/sample'),
                type: 'text/plain; charset=UTF-8;',
                filename: "Sample #{Time.current.to_formatted_s(:db)}.txt"
    elsif params[:demo]
      send_data render_to_string(partial: 'demo/download/demo'),
                type: 'text/plain; charset=UTF-8;',
                filename: "Demo #{Time.current.to_formatted_s(:db)}.txt"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/demo/_download_options.html.erb
<div id="download_options">
    <%= button_to "View download Options", show_options_path,
       :remote => true,
       :method => "post" %>
</div>

app/views/demo/_downloads_list.html.erb
<h3>Your download options are: </h3>
<ul>
  <li class='one'><%= link_to "Data download", download_path(data: true), :method => "post" %></li>
  <li class='two'><%= link_to "Sample download", download_path(sample: true), :method => "post" %></li>
  <li class='three'><%= link_to "Demo download", download_path(demo: true), :method => "post" %></li>
</ul>

<%= button_to "Hide download Options", hide_options_path,
   :remote => true,
   :method => "post" %>

app/views/demo/download/_data.html.erb
Data view contents

app/views/demo/download/_demo.html.erb
Demo view contents

app/views/demo/download/_sample.html.erb
Sample view contents

app/views/demo/hide_options.js.erb
$('#download_options').html("<%= j (render 'demo/download_options') %>");

app/views/demo/home.html.erb
<h1>AJAX Demo</h1>

<%= render 'demo/download_options' %>

app/views/demo/show_options.js.erb
$('#download_options').html("<%= j (render 'demo/downloads_list') %>");
$('#download_options').slideDown(350);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>